### ISSUE TITLE
About page: Curved design on bottom of image not yet implemented (see images)

### ISSUE THREAD

**Issue by charmaine-rabano** [MCL-ACM/acm.mcl-ccis.net#14]
Expected: 
![image](https://user-images.githubusercontent.com/75057081/158193179-781a7517-e2fe-45f1-8bc4-71fcfa7397b8.png)

Current:
![image](https://user-images.githubusercontent.com/75057081/158193256-6be14e33-93d5-4932-8d05-6dd5a9072e9f.png)

**Comment by karlopenguini** [comment]
Resolved,

Solution: 
https://github.com/MCL-ACM/acm.mcl-ccis.net/pull/13/commits/b9f28de51f10a2ac58977e068819e96a6fc76c1e
