### ISSUE TITLE
Buttons in website are inconsistent with those in the design

### ISSUE THREAD

**Issue by LipatJob** [MCL-ACM/acm.mcl-ccis.net#17]
Design
![image](https://user-images.githubusercontent.com/35028794/158287057-a1a54cb5-9ceb-466f-9567-db999161fa5e.png)

Website
![image](https://user-images.githubusercontent.com/35028794/158286977-c837c5e3-4acb-4ac9-8a43-659c9458afc6.png)

Buttons in the website feel thinner

**Comment by karlopenguini** [comment]
Try to set the default font as Roboto for the whole project in global.css or tailwind config

**Comment by karlopenguini** [comment]
fonts for buttons are Exo 2, will try to fix

**Comment by LipatJob** [comment]
See #26
