### ISSUE TITLE
Cannot Cycle Between Events in Event Card in the Home Page

### ISSUE THREAD

**Issue by LipatJob** [MCL-ACM/acm.mcl-ccis.net#18]

**Comment by karlopenguini** [comment]
Already Implemented, please check recent commit https://github.com/MCL-ACM/acm.mcl-ccis.net/commit/c379cf8ff594fa1fc6018861c6eb3f97657f37b2

**Comment by karlopenguini** [comment]
however, im still trying to implement the dot animations in event card component
