### ISSUE TITLE
Dev branch wont build

### ISSUE THREAD

**Issue by karlopenguini** [MCL-ACM/acm.mcl-ccis.net#35]
![image](https://user-images.githubusercontent.com/85627049/158736771-226a0648-d12a-49a2-8fda-fee030c5080a.png)

**Comment by LipatJob** [comment]
will fix

**Comment by LipatJob** [comment]
works fine for me. Try pulling?

**Comment by karlopenguini** [comment]
I tried cloning it again, i still cant build it 
![image](https://user-images.githubusercontent.com/85627049/158738360-c2621a06-6698-458d-8ba5-2b956ee875ea.png)

**Comment by karlopenguini** [comment]
Issue still persists, picture below is from new clone 

![158738360-c2621a06-6698-458d-8ba5-2b956ee875ea](https://user-images.githubusercontent.com/85627049/158738563-d4ff73c0-c429-42c7-aad3-6569a7738222.png)

**Comment by karlopenguini** [comment]
Can develop but build yields the error, will keep this issue open unless its not necessary

**Comment by karlopenguini** [comment]
fixed
