### ISSUE TITLE
Events Modal Improvements

### ISSUE THREAD

**Issue by LipatJob** [MCL-ACM/acm.mcl-ccis.net#55]
When there's many texts, the modal looks like this:
![image](https://user-images.githubusercontent.com/35028794/159488616-b4d7ea91-20f8-488f-80b3-f0f4d30ffc85.png)

The image size should be consistent even when text changes

How it looks like with few texts
![image](https://user-images.githubusercontent.com/35028794/159488977-2da89f6f-cf5b-4f50-9c5c-a9d688a426a3.png)

How it looks like with a lot of text
![image](https://user-images.githubusercontent.com/35028794/159489028-3615313a-b334-4777-b447-cae094d6a3a0.png)

**Comment by karlopenguini** [comment]
Fixed, check recent push
