### ISSUE TITLE
Home, About, Member Hero sections larger than it should be in large screens

### ISSUE THREAD

**Issue by karlopenguini** [MCL-ACM/acm.mcl-ccis.net#56]
#52 
^ related issue

**Comment by karlopenguini** [comment]
most of the elements are really large

**Comment by karlopenguini** [comment]
![image](https://user-images.githubusercontent.com/85627049/160116757-af01e84e-d92f-4b26-81f8-ec2131647c1e.png)

![image](https://user-images.githubusercontent.com/85627049/160116786-2de68aa1-911d-4dfd-a5e2-598578a984ea.png)

![image](https://user-images.githubusercontent.com/85627049/160116895-0f3926c1-54f8-4a24-97ef-f7fbb79af82f.png)

![image](https://user-images.githubusercontent.com/85627049/160116925-88ee3cb2-a951-4c5c-8aa3-1d12e9c1faab.png)

![image](https://user-images.githubusercontent.com/85627049/160116966-fb6d0f54-8305-4aee-a8d3-9d5492356963.png)

![image](https://user-images.githubusercontent.com/85627049/160117000-30595a46-7869-4b5f-aaeb-3bdfb6f5f15b.png)

**Comment by LipatJob** [comment]
See:
23857c27d7c2261dc8044fbc6f4b1660f21e29a0
