### ISSUE TITLE
Styling duplicate in /components/home/EventSection.jsx

### ISSUE THREAD

**Issue by karlopenguini** [MCL-ACM/acm.mcl-ccis.net#61]
![image](https://user-images.githubusercontent.com/85627049/159941285-df0e47c7-62c6-4ee6-a9fc-ccf1ac66439f.png)

**Comment by LipatJob** [comment]
Fixed. See https://github.com/MCL-ACM/acm.mcl-ccis.net/commit/23857c27d7c2261dc8044fbc6f4b1660f21e29a0
